[package]
name = "E8_17"
version = "0.1.0"
authors = ["Github2019 <ffpsping@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
